% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Jan 13 11:17:01 PST 1994 by kalsow
%

import (ui)
module (TypeIn)
implementation (TypeInTest)
program (TypeInTest)
