% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Jan 13 10:38:58 PST 1994 by kalsow
%

import (ui)
module (TypeIn)
module (FocusFilter)
implementation (TypeInTest)
program (TypeInTest)
