# Makefile generated by imake - do not edit!
# $XConsortium: imake.c,v 1.48 89/10/10 18:33:21 jim Exp $
#
# The cpp used on this machine replaces all newlines and multiple tabs and
# spaces in a macro expansion with a single space.  Imake tries to compensate
# for this, but is not always successful.
#

CPU_TYPE = SPARC

PREFIX = /usr/local
INSTALL_PREFIX = $(PREFIX)

BIN = bin
BIN_USE     = $(PREFIX)/$(BIN)
BIN_INSTALL = $(INSTALL_PREFIX)/$(BIN)

PUB = include/m3
PUB_USE     = $(PREFIX)/$(PUB)
PUB_INSTALL = $(INSTALL_PREFIX)/$(PUB)

LIB = lib/m3
LIB_USE     = $(PREFIX)/$(LIB)
LIB_INSTALL = $(INSTALL_PREFIX)/$(LIB)

GNUEMACS_INSTALL = $(INSTALL_PREFIX)/lib/elisp

MAN = man
MAN_USE  = $(PREFIX)/$(MAN)
MAN_INSTALL = $(INSTALL_PREFIX)/$(MAN)

XLIBPATH = /usr/local/lib
XLIB     = -lX11

CC = /bin/cc

CC_WARNS_FOR_UNKNOWN_FILES = 1

CC_G = @-g@

CC_O = @-O@

KEEP_LIBRARIES_RESOLVED = 0

CFLAGS =

M3OPT = -g

BOOTOPT = -g

IMAKEFLAGS =

SHELL = /bin/sh

CPP = /lib/cpp

MAKE = make

SEP   = @
PASS0 = @$(LIB_USE)/m3compiler@
PASS1 = @$(CC)@
PASS2 = @$(CC)@
PASS3 = @/bin/ar@cru@
PASS4 = @ranlib@
PASS5 = @/bin/ld@-A@
OVERLAY_0 = @-g@
OVERLAY_1 = @-lc@
BASE_ARGS = @-N@

SERVER_LIMIT = 0

DEFPATH = .:$(PUB_USE)

LIBPATH = .:$(LIB_USE):$(XLIBPATH)

LINKBFILES = @-lm@
LINKFILES = @-lm3@-lm@

LINKCOVER  = $(LIB_USE)/report_coverage.o

INCL = $(LIB_USE)

TEMPLATE = toplevel.tmpl

all::

M3        = $(BIN_USE)/m3

M3FLAGS   = -w1 -make -why
M3DEFPATH =
M3LIBPATH =
DO_M3     = $(M3) $(M3FLAGS) $(M3OPT) $(M3OPTIONS) $(M3DEFPATH) $(M3LIBPATH)

X11LIBS   = -L$(XLIBPATH) -lXaw -lXmu -lXext -lXt $(XLIB)
M3X11LIBS = -lm3X11R4 $(X11LIBS)
UILIB = -lm3ui -lm3X11R4 -L$(XLIBPATH) $(XLIB)
FORMSVBTLIB = -lm3formsvbt -lm3vbtkit $(UILIB)
ZEUSLIB = -lm3mgkit -lm3mg -lm3zeus -lm3codeview $(FORMSVBTLIB)

TANGLEFLAGS = -L'<*LINE %L "%F" *>%N'
WEAVEFLAGS = -n

  import ("libm3")
  import ("tcp")
  import ("netobj")
  import ("idl")
  import ("ui")
  import ("formsvbt")

.RSRC_MODIFIED:: ./ "bankmacro.fv"
	@touch .RSRC_MODIFIED

.RSRC_MODIFIED:: ./ "bank-background.fv"
	@touch .RSRC_MODIFIED

all:: B.m3 B.i3
clean:: FRC
	rm -f B.i3 B.m3 .RSRC_MODIFIED
B.i3 B.m3: .RSRC_MODIFIED
	$(BIN_USE)/m3bundle -name B $(RSRC_CMD)

  idl_options ("-emit netobj -emit DII -inherit methods")


  idl_interface (bank)
  netobj (bank, T)
  netobj (bank, account)


all:: server
clean:: ; rm -f server
server: FRC ; $(DO_M3) -o server $(PGM_SOURCES) $(IMPORT_LIBS)

scratch:: clean

tidy::
	find . \( -name ",*" -o -name ".,*" -o -name ".emacs_[0-9]*" \
	    -o -name "*~" -o -name core -o -name a.out \) -print | xargs rm -f

clean:: tidy
	find . \( -name "*.o" -o -name "*.io" -o -name "*.ix" \
\
		  -o -name "*.mo" -o -name "*.mx" \) -print | xargs rm -f
	rm -f .makefile .m3path* .PGM_SOURCES .EXPORTED_BIN .RSRC_CMD
	rm -f .m3imports*

FRC:

PGM_SOURCES = \
  B.i3 \
  B.m3 \
  ./DII.i3 \
  ./DII.m3 \
  ./Server.m3
RSRC_CMD = \
  -element \
  macro \
  ./ \
  -element \
  background \
  ./
