% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Jan 13 11:10:09 PST 1994 by kalsow
%

import (ui)
implementation (Spot)
program (Spot)
