% bootstrap Modula-3 makefile

boot_is ("Mx")
boot_ms ("Mx")
boot_is ("MxIn")
boot_ms ("MxIn")
boot_is ("MxOut")
boot_ms ("MxOut")
boot_is ("MxMerge")
boot_ms ("MxMerge")
boot_is ("MxCheck")
boot_ms ("MxCheck")
boot_is ("MxGen")
boot_ms ("MxGen")
boot_is ("MxVS")
boot_ms ("MxVS")
boot_is ("MxRep")
boot_ms ("MxRep")
boot_is ("MxMap")
boot_ms ("MxMap")
boot_is ("MxSet")
boot_ms ("MxSet")
boot_is ("MxVSSet")
boot_ms ("MxVSSet")
boot_is ("MxIO")
boot_ms ("MxIO")


boot_lib ("m3link")
